

### register for Musire
post https://attractive-three-hippopotamus.glitch.me/api/Users/register HTTP/1.1
Content-Type: application/json

{
   "username": "musire",
   "email": "mcmusire@gmail.com",
   "password": "pokemon1",
   "password2": "pokemon1"
}

### register for Thug

post https://attractive-three-hippopotamus.glitch.me/api/Users/register HTTP/1.1
Content-Type: application/json

{
   "username": "thug",
   "email": "thug@life.com",
   "password": "thug123",
   "password2": "thug123"
}

### login for Thug

post http://localhost:5000/api/Users/login HTTP/1.1
Content-Type: application/json

{
   "email": "thug@life.com",
   "password": "thug123"
}

### login for God

post http://localhost:5000/api/Users/login HTTP/1.1
Content-Type: application/json

{
   "email": "god@heaven.com",
   "password": "god123"
}
